language: scala
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - juan.rodriguez.hortala@gmail.com

scala:
   - 2.10.5
jdk:
  - oraclejdk7
script: 
  - sbt ++$TRAVIS_SCALA_VERSION test
